### ISSUE TITLE
v3.0.0 doesn't seem to convert the absolute paths to relative anymore

### ISSUE THREAD

**Issue by zenril** [ericmorand/gulp-twing#21]
I seem to be having this issue as well.

----

v3.0.0 doesn't seem to be working with the configuration I've posted above. It seems that path.relative has been removed [here](https://github.com/ericmorand/gulp-twing/blob/v2.0.0/src/index.js#L26).

Just wondering if I should be passing some extra option to the env/loader to make this work?

_Originally posted by @kabadesu in https://github.com/ericmorand/gulp-twing/issues/19#issuecomment-454951333_

**Comment by ericmorand** [comment]
Yes, it's a deliberate move...that I failed to implement correctly.

The original idea was to stop forcing the file loader to be set to `.`. That doesn't make sense to enforce a single file loader configuration especially because it's totally supported by Twing to chain loaders - for example to have file loaders dedicated to different location, like "custom" and "default" template locations that are resolved in that order.

Anyway, I forgot to test that change and it doesn't work. I'm working on it right now.

**Comment by ericmorand** [comment]
Issue fixed in 3.0.1.

**Comment by kabadesu** [comment]
This works perfectly for me now. Thanks very much.
