### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by olets** [ericmorand/gulp-twing#5]
I'm getting this error when using the README example.

Terminal log:

```shell
$ gulp
path/to/gulp-twing-test/node_modules/twing/lib/twing/environment.js:214
    async render(name, context = {}) {
          ^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (path/to/gulp-twing-test/node_modules/twing/lib/twing.js:30:23)
    at Module._compile (module.js:571:32)
```

Gulpfile

```js
let gulp = require('gulp');
let gulpTwing = require('gulp-twing');
let Twing = require('twing');
let loader = new Twing.TwingLoaderFilesystem('twing-test');
let env = new Twing.TwingEnvironment(loader);

gulp
    .src('twing-test')
    .pipe(gulpTwing(env))
    .dest('twing-dest')
;
```

Files:

```
gulp-twing-test
    - node_modules ƒ
    - twing-test ƒ
        - index.html.twig (contents: "test")
```

Package.json dependencies:

```
"gulp": "^3.9.1",
"gulp-twing": "^1.0.0",
"twing": "^0.9.0"
```

**Comment by ericmorand** [comment]
Thanks for the report.

First thing first, the example on the README may be one of the worst README example ever. It is simply totally wrong. :D

I'll fix it with a sample that actually work:

```
let gulp = require('gulp');
let gulpTwing = require('gulp-twing');
let Twing = require('twing');
let loader = new Twing.TwingLoaderFilesystem('/');
let env = new Twing.TwingEnvironment(loader);

gulp
    .src('**/*.twig')
    .pipe(gulpTwing(env))
    .pipe(gulp.dest('dest'))
;
```

Second, which version of node are you using? async being not recognized, I suspect it's node < 7.6.0.

**Comment by olets** [comment]
Gotcha cool, I see my problem was setting `TwingLoaderFilesystem` to the template source directory rather than `/`. Fixed! Works!

What's an example for when you _wouldn't_ set it to `/`? Is that just targeting the parent of the `node_modules` where Twing is installed? <https://ericmorand.github.io/twing/api.html> makes it sound like it's the main template directory.

**Comment by ericmorand** [comment]
If you set it to something else, all templates will be resolved relatively to one of the registered paths.

For clarity, let's set a single path to the loader:

`let loader = new Twing.TwingLoaderFilesystem('tpl');`

Without second argument (the `rootPath`), `tpl `will be resolved relative to process.cwd().

All template will then be loaded relatively to that path. Let's assume the following project:

```
tpl
\ foo.twig
\ bar.twig
foo-bar.twig
```

Only foo.twig and bar.twig are located inside the `tpl `directory. In order to load thoses templates one would have to do:

```
let foo = env.loadTemplate('foo.twig');
let bar= env.loadTemplate('bar.twig');
let fooBar = env.loadTemplate('../foo-bar.twig');
```

Of course, passing '/' as the registered path of the loader will set the root of the filesystem as the path used to resolve the templates. So:

```
let loader = new Twing.TwingLoaderFilesystem('/');
let env = new TwingEnvironment(loader);

let foo = env.loadTemplate('foo.twig');
```

Will throw an error because `/foo.twig` doesn't exist. 

But, since gulp is passing a file with an absolute path to the plugin, it's the only way to have the loader resolve the templates.

I still have to review that #3 to see if it can make gulp-twing more open-minded about this.

**Comment by ericmorand** [comment]
I close. I you feel it needs to be reopen, just add a comment.
